name: Lint
on: [push]
jobs:
  build:
    name: Lint on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['12.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint
